![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [6]:
import numpy as np
print(np.__version__)

2.2.4


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [7]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [8]:
my_array_true = np.full([3,3],True)
print(my_array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [9]:
my_array %2==1



array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [10]:
my_array[my_array % 2==1]
print(my_array[my_array % 2==1])

##impares = my_array[my_array % 2 != 0]

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [11]:
new_array = np.copy(my_array)
print(new_array)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
new_array = np.copy(my_array)
new_array[new_array % 2 != 0] = -1
print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [13]:
my_array2 = np.copy(my_array)
print(my_array2)
new_array2= np.where(my_array2 % 2!=0, -1, my_array2)
print(new_array2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [14]:
my_array
print(my_array)


[0 1 2 3 4 5 6 7 8 9]


In [15]:
x = my_array
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [16]:

y = x.reshape((2,5))
print(y)



[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

resultado = np.concatenate ((a,b))
resultado = np.vstack([a,b])
print(resultado)



## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

resultado_2 = np.hstack((a,b))
print(resultado_2)

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
elementos_comun = np.intersect1d(a,b)
##common_elements = np.intersect1d(a, b)

##print(common_elements)
print( elementos_comun)


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [ ]:
##Para concatenar matrices, `numpy` tiene varios métodos: `np.concatenate`, `np.vstack` o 
# `np.hstack`. Lo único que hay que tener en cuenta es que coincidan las dimensiones, 
# para que el concatenado sea correcto.

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [46]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
my_array_por10 = my_array * 10
print(my_array_por10)

[ 0 10 20 30 40 50 60 70 80 90]


In [49]:
primer_array = my_array[0]
print(primer_array)



0


In [50]:
ultimo_array = my_array [-1]
print(ultimo_array)

9


In [ ]:
print(my_array[1:8])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [52]:


my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Imprimir el array
print(my_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [18]:
my_secuencia = np.arange(1, 50, 3)
print(my_secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [19]:
# Crear una secuencia aleatoria de 4 matrices de 5x3
random_sequence = np.random.rand(4, 5, 3)

# Imprimir la secuencia
print(random_sequence)

[[[0.90083302 0.23375637 0.77371182]
  [0.82021106 0.58293658 0.13883777]
  [0.12564691 0.58638325 0.12243738]
  [0.55022726 0.39910948 0.1047906 ]
  [0.1791998  0.00107453 0.44840699]]

 [[0.37044247 0.28182893 0.18020957]
  [0.20969691 0.3432785  0.82281615]
  [0.18130075 0.49857809 0.00130717]
  [0.160307   0.50972982 0.51297081]
  [0.52183939 0.25460368 0.77772421]]

 [[0.49353685 0.01296524 0.01643532]
  [0.25681165 0.15645401 0.87498658]
  [0.74750491 0.1313867  0.5114389 ]
  [0.40783405 0.1977643  0.72546802]
  [0.94287173 0.84668889 0.96099364]]

 [[0.42178414 0.8316175  0.01885577]
  [0.09059625 0.87484227 0.45359429]
  [0.95057827 0.08917041 0.96212367]
  [0.58353084 0.15138763 0.52442286]
  [0.23552674 0.46260787 0.07269027]]]


## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [22]:
# Crear una matriz de 10x1 compuesta por False
matrix = np.full((10, 1), False)



In [23]:
# Transformar la matriz en una de 2x5
reshaped_matrix = matrix.reshape(2, 5)

# Imprimir la matriz resultante
print(reshaped_matrix)

[[False False False False False]
 [False False False False False]]


## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [ ]:

x = np.random.randint(10, 20, size = (5,2,6))

print =(x.size)


In [25]:
print =(x. ndim)

In [26]:
print=(x.shape)